### ISSUE TITLE
Support more systems (OS X, Linux distributions, BSD's, etc.)

### ISSUE THREAD

**Issue by tony** [pyston/pyston#1068]
Carried on from #998 (OS X support) and #1017 (FreeBSD build issue).  Let's try to get pyston building across more systems.
- [x] Remove bash-isms in Makefile and Tools #1069
  
  Not all systems have bash, in many cases this is simple as changing a shebang
- [x] Check for presence of `gmake` for BSD systems and have underlying dependencies build with gmake. #1071
  
  FreeBSD uses its own make which isn't compatible with GNU Make, however, it can run any GNU Makefile via `gmake`.
- [x] Fix finding gmp.h on FreeBSD #1017 
- [ ] Get libunwind working with OS X #456, possibly with http://opensource.apple.com/source/libunwind/

I may add more I find on the tracker and put them here.

There's also a fair chance I may end up ultimately closing the issue. Every time a new platform added for pyston would mean someone would need to take responsibility for it.

**Comment by kmod** [comment]
Thanks for looking into this!  Will be very exciting to get these up and running.

As a follow-up I think it'd be great if we could get some sort of continuous-integration set up for these new platforms, so that for those of us without access to them we can at least see if we broke them.  Maybe once BSD is working we can hunt for a hosted CI service that supports it.

**Comment by tony** [comment]
@kmod Hey! You've been missed!  Hope all is going well

**Comment by kmod** [comment]
Thanks @tony !
